/*
 * SwaggerでマンガAPIを遊ぶ
 * マンガのためのAPI
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Swaggerapi);
  }
}(this, function(expect, Swaggerapi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Chapter', function() {
      beforeEach(function() {
        instance = new Swaggerapi.Chapter();
      });

      it('should create an instance of Chapter', function() {
        // TODO: update the code to test Chapter
        expect(instance).to.be.a(Swaggerapi.Chapter);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property pages (base name: "pages")', function() {
        // TODO: update the code to test the property pages
        expect(instance).to.have.property('pages');
        // expect(instance.pages).to.be(expectedValueLiteral);
      });

    });
  });

}));
