/*
 * SwaggerでマンガAPIを遊ぶ
 * マンガのためのAPI
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Swaggerapi);
  }
}(this, function(expect, Swaggerapi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Comment', function() {
      beforeEach(function() {
        instance = new Swaggerapi.Comment();
      });

      it('should create an instance of Comment', function() {
        // TODO: update the code to test Comment
        expect(instance).to.be.a(Swaggerapi.Comment);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property userId (base name: "userId")', function() {
        // TODO: update the code to test the property userId
        expect(instance).to.have.property('userId');
        // expect(instance.userId).to.be(expectedValueLiteral);
      });

      it('should have the property titleId (base name: "titleId")', function() {
        // TODO: update the code to test the property titleId
        expect(instance).to.have.property('titleId');
        // expect(instance.titleId).to.be(expectedValueLiteral);
      });

      it('should have the property body (base name: "body")', function() {
        // TODO: update the code to test the property body
        expect(instance).to.have.property('body');
        // expect(instance.body).to.be(expectedValueLiteral);
      });

    });
  });

}));
