/*
 * SwaggerでマンガAPIを遊ぶ
 * マンガのためのAPI
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Chapter'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Chapter'));
  } else {
    // Browser globals (root is window)
    if (!root.Swaggerapi) {
      root.Swaggerapi = {};
    }
    root.Swaggerapi.Manga = factory(root.Swaggerapi.ApiClient, root.Swaggerapi.Chapter);
  }
}(this, function(ApiClient, Chapter) {
  'use strict';

  /**
   * The Manga model module.
   * @module model/Manga
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Manga</code>.
   * @alias module:model/Manga
   * @class
   * @param id {Number} 
   */
  var exports = function(id) {
    this.id = id;
  };

  /**
   * Constructs a <code>Manga</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Manga} obj Optional instance to populate.
   * @return {module:model/Manga} The populated <code>Manga</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('releaseDate'))
        obj.releaseDate = ApiClient.convertToType(data['releaseDate'], 'Date');
      if (data.hasOwnProperty('chapters'))
        obj.chapters = ApiClient.convertToType(data['chapters'], [Chapter]);
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {Date} releaseDate
   */
  exports.prototype.releaseDate = undefined;

  /**
   * @member {Array.<module:model/Chapter>} chapters
   */
  exports.prototype.chapters = undefined;

  return exports;

}));
