/*
 * SwaggerでマンガAPIを遊ぶ
 * マンガのためのAPI
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Comment'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Comment'));
  } else {
    // Browser globals (root is window)
    if (!root.Swaggerapi) {
      root.Swaggerapi = {};
    }
    root.Swaggerapi.CommentApi = factory(root.Swaggerapi.ApiClient, root.Swaggerapi.Comment);
  }
}(this, function(ApiClient, Comment) {
  'use strict';

  /**
   * Comment service.
   * @module api/CommentApi
   * @version 1.0.0
   */

  /**
   * Constructs a new CommentApi. 
   * @alias module:api/CommentApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getCommentsByTitleId operation.
     * @callback module:api/CommentApi~getCommentsByTitleIdCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Comment>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get comment by title_id
     * @param {Number} titleId ID of title id
     * @param {module:api/CommentApi~getCommentsByTitleIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Comment>}
     */
    this.getCommentsByTitleId = function(titleId, callback) {
      var postBody = null;

      // verify the required parameter 'titleId' is set
      if (titleId === undefined || titleId === null) {
        throw new Error("Missing the required parameter 'titleId' when calling getCommentsByTitleId");
      }


      var pathParams = {
      };
      var queryParams = {
        'titleId': titleId,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [Comment];

      return this.apiClient.callApi(
        '/comments', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the putCommentByTitleId operation.
     * @callback module:api/CommentApi~putCommentByTitleIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send comment to title
     * @param {Number} titleId ID of title id
     * @param {Number} userId ID of user id
     * @param {String} body comment
     * @param {module:api/CommentApi~putCommentByTitleIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.putCommentByTitleId = function(titleId, userId, body, callback) {
      var postBody = null;

      // verify the required parameter 'titleId' is set
      if (titleId === undefined || titleId === null) {
        throw new Error("Missing the required parameter 'titleId' when calling putCommentByTitleId");
      }

      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling putCommentByTitleId");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling putCommentByTitleId");
      }


      var pathParams = {
      };
      var queryParams = {
        'titleId': titleId,
        'userId': userId,
        'body': body,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/comments', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
