<?php
/**
 * CommentApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SwaggerでマンガAPIを遊ぶ
 *
 * マンガのためのAPI
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Swagger\Server\Model\Comment;

/**
 * CommentApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Swagger\Server\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface CommentApiInterface
{

    /**
     * Operation getCommentsByTitleId
     *
     * Get comment by title_id
     *
     * @param  int $titleId  ID of title id (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\Comment[]
     *
     */
    public function getCommentsByTitleId($titleId, &$responseCode, array &$responseHeaders);

    /**
     * Operation putCommentByTitleId
     *
     * Send comment to title
     *
     * @param  int $titleId  ID of title id (required)
     * @param  int $userId  ID of user id (required)
     * @param  string $body  comment (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function putCommentByTitleId($titleId, $userId, $body, &$responseCode, array &$responseHeaders);
}
